import { supabase } from '../lib/supabase';

class GuidedOnboardingService {
  constructor() {
    this.tours = {
      profileMenu: {
        id: 'profile-menu',
        name: 'Profile Menu Tour',
        steps: [
          {
            target: '[data-tour="profile-menu"]',
            title: 'Welcome to Your Profile',
            content: 'Access your profile settings, VP balance, and achievements here.',
            position: 'bottom'
          },
          {
            target: '[data-tour="vp-balance"]',
            title: 'VP Balance',
            content: 'Your Vottery Points (VP) are displayed here. Earn VP by voting and participating!',
            position: 'bottom'
          },
          {
            target: '[data-tour="achievements"]',
            title: 'Achievements',
            content: 'Track your progress and unlock badges as you engage with the platform.',
            position: 'left'
          }
        ]
      },
      votingMechanics: {
        id: 'voting-mechanics',
        name: 'Voting Mechanics Tour',
        steps: [
          {
            target: '[data-tour="voting-types"]',
            title: 'Voting Types',
            content: 'Choose from Plurality, Ranked Choice, Approval, or Plus/Minus voting.',
            position: 'right'
          },
          {
            target: '[data-tour="cast-vote"]',
            title: 'Cast Your Vote',
            content: 'Select your choice and click here to submit your vote securely.',
            position: 'top'
          },
          {
            target: '[data-tour="vote-receipt"]',
            title: 'Vote Receipt',
            content: 'Receive a blockchain-verified receipt for transparency and security.',
            position: 'bottom'
          }
        ]
      },
      creatorTools: {
        id: 'creator-tools',
        name: 'Creator Tools Tour',
        steps: [
          {
            target: '[data-tour="create-election"]',
            title: 'Create Elections',
            content: 'Start creating your own elections and engage your audience.',
            position: 'bottom'
          },
          {
            target: '[data-tour="earnings-dashboard"]',
            title: 'Earnings Dashboard',
            content: 'Track your creator earnings with our 70% revenue share model.',
            position: 'left'
          },
          {
            target: '[data-tour="analytics"]',
            title: 'Analytics',
            content: 'Monitor your election performance and audience engagement.',
            position: 'top'
          }
        ]
      },
      aiFeatures: {
        id: 'ai-features',
        name: 'AI Features Tour',
        steps: [
          {
            target: '[data-tour="ai-recommendations"]',
            title: 'AI Recommendations',
            content: 'Get personalized content recommendations powered by multiple AI models.',
            position: 'right'
          },
          {
            target: '[data-tour="ai-quests"]',
            title: 'AI-Generated Quests',
            content: 'Complete personalized quests generated by OpenAI to earn bonus VP.',
            position: 'bottom'
          },
          {
            target: '[data-tour="ai-insights"]',
            title: 'AI Insights',
            content: 'View AI-powered analytics and predictions for elections.',
            position: 'left'
          }
        ]
      }
    };
  }

  // Get tour by ID
  getTour(tourId) {
    return this.tours?.[tourId] || null;
  }

  // Get all available tours
  getAllTours() {
    return Object.values(this.tours);
  }

  // Check if user has completed tour
  async hasCompletedTour(userId, tourId) {
    try {
      const { data, error } = await supabase?.from('user_onboarding_progress')?.select('completed_tours')?.eq('user_id', userId)?.single();

      if (error && error?.code !== 'PGRST116') throw error;

      return data?.completed_tours?.includes(tourId) || false;
    } catch (error) {
      console.error('Check tour completion error:', error);
      return false;
    }
  }

  // Mark tour as completed
  async completeTour(userId, tourId) {
    try {
      const { data: existing } = await supabase?.from('user_onboarding_progress')?.select('completed_tours')?.eq('user_id', userId)?.single();

      const completedTours = existing?.completed_tours || [];
      
      if (!completedTours?.includes(tourId)) {
        completedTours?.push(tourId);
      }

      const { error } = await supabase?.from('user_onboarding_progress')?.upsert({
          user_id: userId,
          completed_tours: completedTours,
          updated_at: new Date()?.toISOString()
        });

      if (error) throw error;

      return true;
    } catch (error) {
      console.error('Complete tour error:', error);
      return false;
    }
  }

  // Skip tour
  async skipTour(userId, tourId) {
    try {
      const { data: existing } = await supabase?.from('user_onboarding_progress')?.select('skipped_tours')?.eq('user_id', userId)?.single();

      const skippedTours = existing?.skipped_tours || [];
      
      if (!skippedTours?.includes(tourId)) {
        skippedTours?.push(tourId);
      }

      const { error } = await supabase?.from('user_onboarding_progress')?.upsert({
          user_id: userId,
          skipped_tours: skippedTours,
          updated_at: new Date()?.toISOString()
        });

      if (error) throw error;

      return true;
    } catch (error) {
      console.error('Skip tour error:', error);
      return false;
    }
  }

  // Get user onboarding progress
  async getUserProgress(userId) {
    try {
      const { data, error } = await supabase?.from('user_onboarding_progress')?.select('*')?.eq('user_id', userId)?.single();

      if (error && error?.code !== 'PGRST116') throw error;

      const allTours = Object.keys(this.tours);
      const completedTours = data?.completed_tours || [];
      const skippedTours = data?.skipped_tours || [];
      const remainingTours = allTours?.filter(
        t => !completedTours?.includes(t) && !skippedTours?.includes(t)
      );

      return {
        completedTours,
        skippedTours,
        remainingTours,
        completionPercentage: (completedTours?.length / allTours?.length) * 100
      };
    } catch (error) {
      console.error('Get user progress error:', error);
      return null;
    }
  }

  // Reset tour progress
  async resetTour(userId, tourId) {
    try {
      const { data: existing } = await supabase?.from('user_onboarding_progress')?.select('*')?.eq('user_id', userId)?.single();

      const completedTours = (existing?.completed_tours || [])?.filter(t => t !== tourId);
      const skippedTours = (existing?.skipped_tours || [])?.filter(t => t !== tourId);

      const { error } = await supabase?.from('user_onboarding_progress')?.upsert({
          user_id: userId,
          completed_tours: completedTours,
          skipped_tours: skippedTours,
          updated_at: new Date()?.toISOString()
        });

      if (error) throw error;

      return true;
    } catch (error) {
      console.error('Reset tour error:', error);
      return false;
    }
  }
}

export default new GuidedOnboardingService();