import * as Web from '../constants/navigationHubRoutes';
const FULL_FEATURE_CERTIFICATION_MODE = true;

const normalizePath = (path) => {
  const value = String(path || '').trim();
  if (!value) return '';
  const withoutHash = value.split('#')[0];
  const withoutQuery = withoutHash.split('?')[0];
  const cleaned = withoutQuery.replace(/\/+$/, '');
  return cleaned || '/';
};

export const BATCH1_ALLOWED_ROUTE_PATHS = new Set([
  '/',
  Web.HOME_FEED_DASHBOARD_ROUTE,
  Web.AUTHENTICATION_PORTAL_ROUTE,
  Web.AUTH_CALLBACK_ROUTE,
  Web.ROLE_UPGRADE_ROUTE,
  Web.ELECTIONS_DASHBOARD_ROUTE,
  Web.VOTE_IN_ELECTIONS_HUB_ROUTE,
  Web.SECURE_VOTING_INTERFACE_ROUTE,
  Web.VOTING_CATEGORIES_ROUTE,
  Web.ELECTION_CREATION_STUDIO_ROUTE,
  Web.VOTE_VERIFICATION_PORTAL_ROUTE,
  Web.BLOCKCHAIN_AUDIT_PORTAL_ROUTE,
  Web.USER_PROFILE_HUB_ROUTE,
  Web.SETTINGS_ACCOUNT_DASHBOARD_ROUTE,
  Web.DIGITAL_WALLET_HUB_ROUTE,
  Web.VOTTERY_POINTS_VP_UNIVERSAL_CURRENCY_CENTER_ROUTE,
  Web.VP_REDEMPTION_MARKETPLACE_CHARITY_HUB_ROUTE,
  Web.UNIFIED_PAYMENT_ORCHESTRATION_HUB_ROUTE,
  Web.STRIPE_CONNECT_ACCOUNT_LINKING_INTERFACE_ROUTE,
  Web.USER_SUBSCRIPTION_DASHBOARD_ROUTE,
  Web.STRIPE_SUBSCRIPTION_MANAGEMENT_CENTER_ROUTE,
  Web.ADMIN_SUBSCRIPTION_ANALYTICS_HUB_ROUTE,
  Web.STRIPE_PAYMENT_INTEGRATION_HUB_ROUTE,
  Web.COUNTRY_RESTRICTIONS_ADMIN_ROUTE,
  Web.PLATFORM_INTEGRATIONS_ADMIN_ROUTE,
  Web.DIRECT_MESSAGING_CENTER_ROUTE,
  Web.NOTIFICATION_CENTER_HUB_ROUTE,
  Web.FRIENDS_MANAGEMENT_HUB_ROUTE,
  Web.ENHANCED_HUBS_DISCOVERY_MANAGEMENT_HUB_ROUTE,
  Web.SOCIAL_ACTIVITY_TIMELINE_ROUTE,
  Web.API_DOCUMENTATION_PORTAL_ROUTE,
  Web.ADMIN_CONTROL_CENTER_ROUTE,
  Web.ADMIN_PLATFORM_LOGS_CENTER_ROUTE,
  Web.BULK_MANAGEMENT_SCREEN_ROUTE,
  Web.MOBILE_ADMIN_DASHBOARD_ROUTE,
  Web.BRAND_ADVERTISER_REGISTRATION_PORTAL_ROUTE,
  Web.VOTTERY_ADS_STUDIO_ROUTE,
  /** Policy surface: Batch-1 kill-switch copy must be reachable for certification / parity tests. */
  Web.PARTICIPATORY_ADS_STUDIO_ROUTE,
  /** Hub parity smoke + finance/gamification regression (routes still role-gated). */
  Web.GAMIFICATION_CAMPAIGN_MANAGEMENT_CENTER_ROUTE,
  Web.GAMIFICATION_REWARDS_MANAGEMENT_CENTER_ROUTE,
  Web.SECURITY_COMPLIANCE_AUTOMATION_CENTER_ROUTE,
  Web.INTERNATIONAL_PAYMENT_DISPUTE_RESOLUTION_CENTER_ROUTE,
  Web.UNIFIED_REVENUE_INTELLIGENCE_DASHBOARD_ROUTE,
  Web.PUBLIC_BULLETIN_BOARD_AUDIT_TRAIL_CENTER_ROUTE,
  Web.ADMIN_QUEST_CONFIGURATION_CONTROL_CENTER_ROUTE,
  Web.STATUS_ROUTE,
  Web.PUBLIC_STATUS_PAGE_ROUTE,
  Web.INTERACTIVE_ONBOARDING_WIZARD_ROUTE,
  Web.AI_GUIDED_INTERACTIVE_TUTORIAL_SYSTEM_ROUTE,
  Web.MULTI_AUTHENTICATION_GATEWAY_ROUTE,
  Web.USER_SECURITY_CENTER_ROUTE,
  Web.CENTRALIZED_SUPPORT_TICKETING_SYSTEM_ROUTE,
  Web.CREATOR_MONETIZATION_STUDIO_ROUTE,
  Web.ENHANCED_HOME_FEED_DASHBOARD_ROUTE,
  // New Admin Dashboard Modules
  Web.ADMIN_AI_CONTENT_MODERATION_ROUTE,
  Web.ADMIN_FRAUD_DETECTION_CENTER_ROUTE,
  Web.ADMIN_NOTIFICATION_INTELLIGENCE_ROUTE,
  Web.ADMIN_REVENUE_INTELLIGENCE_ROUTE,
  Web.ADMIN_SOCIAL_ACTIVITY_ANALYTICS_ROUTE,
  Web.ADMIN_SOCIAL_ENGAGEMENT_ANALYTICS_ROUTE,
  Web.ADMIN_SOCIAL_TIMELINE_ANALYTICS_ROUTE,
  Web.ADMIN_ACCESSIBILITY_ANALYTICS_ROUTE,
  Web.ADMIN_SLACK_INCIDENTS_ROUTE,
  Web.ADMIN_ELECTION_MODERATION_HUB_ROUTE,
]);

export function isBatch1RouteAllowed(path) {
  if (FULL_FEATURE_CERTIFICATION_MODE) return true;
  const normalized = normalizePath(path);
  if (!normalized) return true;
  return BATCH1_ALLOWED_ROUTE_PATHS.has(normalized);
}
