/**
 * Map route path (no leading slash) to platform_feature_toggles.feature_key.
 * Used to gate routes by admin On/Off panel. Keys must match DB feature_key.
 * If a path is not in this map, the route is not gated by feature toggle.
 * Keep feature_key values aligned with Flutter `lib/config/route_feature_keys.dart`.
 */
export const ROUTE_FEATURE_KEYS = {
  'election-creation-studio': 'election_creation',
  'open-ai-quest-generation-studio': 'election_creation',
  'vote-verification-portal': 'vote_verification_portal',
  'blockchain-audit-portal': 'blockchain_verification',
  'secure-voting-interface': 'secure_voting_interface',
  'plus-minus-voting-interface': 'secure_voting_interface',
  'vote-in-elections-hub': 'vote_in_elections_hub',
  'voting-categories': 'voting_categories',
  'collaborative-voting-room': 'collaborative_voting_room',
  'location-based-voting': 'location_based_voting',
  'vottery-points-vp-universal-currency-center': 'vp_universal_currency_center',
  'vp-redemption-marketplace-charity-hub': 'vp_redemption_marketplace_charity_hub',
  'comprehensive-gamification-admin-control-center': 'gamified_elections',
  'gamification-multi-language-intelligence-center': 'gamified_elections',
  'gamification-progression-achievement-hub': 'gamified_elections',
  'premium-3d-slot-machine-integration-hub': 'gamified_elections',
  'vp-economy-health-monitor-dashboard': 'gamified_elections',
  'dynamic-cpe-pricing-engine-dashboard': 'sponsored_elections_schema_cpe_management_hub',
  'query-performance-monitoring-dashboard': 'live_platform_monitoring_dashboard',
  'platform-gamification-core-engine': 'gamified_elections',
  'gamification-campaign-management-center': 'gamified_elections',
  'gamification-rewards-management-center': 'gamified_elections',
  'admin-quest-configuration-control-center': 'dynamic_quest_management_dashboard',
  'dynamic-quest-management-dashboard': 'dynamic_quest_management_dashboard',
  'election-prediction-pools-interface': 'prediction_pools',
  'prediction-pool-notifications-hub': 'prediction_pools',
  'unified-gamification-dashboard': 'unified_gamification_dashboard',
  'seasonal-challenges': 'seasonal_challenges',
  'user-profile-hub': 'user_profile_hub',
  'digital-wallet-hub': 'digital_wallet_hub',
  'direct-messaging-center': 'direct_messaging',
  'notification-center-hub': 'notification_center_hub',
  'friends-management-hub': 'friends_management_hub',
  'social-activity-timeline': 'social_activity_timeline',
  'settings-account-dashboard': 'settings_account_dashboard',
  'personal-analytics-dashboard': 'personal_analytics_dashboard',
  'real-time-analytics-dashboard': 'real_time_analytics_dashboard',
  'live-platform-monitoring-dashboard': 'live_platform_monitoring_dashboard',
  'advanced-platform-monitoring-event-tracking-hub': 'live_platform_monitoring_dashboard',
  'datadog-apm-performance-intelligence-center': 'live_platform_monitoring_dashboard',
  'enhanced-real-time-supabase-integration-hub': 'live_platform_monitoring_dashboard',
  'user-analytics-dashboard': 'user_analytics_dashboard',
  'enhanced-analytics-dashboards': 'user_analytics_dashboard',
  'feature-performance-dashboard': 'user_analytics_dashboard',
  'user-security-center': 'user_security_center',
  'participatory-ads-studio': 'participatory_advertising',
  'vottery-ads-studio': 'participatory_advertising',
  'campaign-management-dashboard': 'campaign_management_dashboard',
  'automated-campaign-optimization-dashboard': 'campaign_optimization_dashboard',
  'campaign-template-gallery': 'campaign_template_gallery',
  'enhanced-real-time-advertiser-roi-dashboard': 'enhanced_real_time_advertiser_roi_dashboard',
  'vottery-ads-admin-config': 'enhanced_real_time_advertiser_roi_dashboard',
  'brand-dashboard-specialized-kpis-center': 'brand_dashboard_specialized_kpis_center',
  'brand-dashboard-specialized-kp-is-center': 'brand_dashboard_specialized_kpis_center',
  'real-time-brand-alert-budget-monitoring-center': 'real_time_brand_alert_budget_monitoring_center',
  'dual-advertising-system-analytics-dashboard': 'dual_advertising_system_analytics_dashboard',
  'ad-network-status-and-split-dashboard': 'dual_advertising_system_analytics_dashboard',
  'ad-sense-revenue-analytics-dashboard': 'dual_advertising_system_analytics_dashboard',
  'ad-slot-manager-inventory-control-center': 'ad_slot_manager_inventory_control_center',
  'dynamic-ad-rendering-fill-rate-analytics-hub': 'dynamic_ad_rendering_fill_rate_analytics_hub',
  'sponsored-elections-schema-cpe-management-hub': 'sponsored_elections_schema_cpe_management_hub',
  'advanced-admin-role-management-system': 'advanced_admin_role_management_system',
  'admin-control-center': 'advanced_admin_role_management_system',
  'bulk-management-screen': 'advanced_admin_role_management_system',
  'mobile-admin-dashboard': 'mobile_admin_dashboard',
  'ai-content-safety-screening-center': 'ai_content_safety_screening_center',
  'content-distribution-control-center': 'content_distribution_control_center',
  'anthropic-content-intelligence-center': 'anthropic_content_intelligence_center',
  'anthropic-advanced-content-analysis-center': 'anthropic_advanced_content_analysis_center',
  'advertiser-analytics-roi-dashboard': 'advertiser_analytics_roi',
  'brand-advertiser-registration-portal': 'brand_advertiser_registration',
  'creator-monetization-studio': 'creator_monetization_studio',
  'age-verification-digital-identity-center': 'age_verification_digital_identity_center',
  'presentation-builder-audience-q-a-hub': 'presentation_builder_audience_qa_hub',
  'creator-success-academy': 'creator_success_academy',
  'enhanced-mcq-creation-studio': 'enhanced_mcq_creation_studio',
  'enhanced-mcq-pre-voting-interface': 'mcq_pre_voting_interface',
  'live-question-injection-management-center': 'live_question_injection_management_center',
  'enhanced-mcq-image-interface': 'enhanced_mcq_image_interface',
  'ai-guided-interactive-tutorial-system': 'ai_guided_interactive_tutorial_system',
  'user-feedback-portal-with-feature-request-system': 'user_feedback_portal_feature_request_system',
  'user-feedback-portal': 'user_feedback_portal_feature_request_system',
  'feature-implementation-tracking-engagement-analytics-center': 'feature_implementation_tracking_engagement_analytics_center',
  'content-moderation-control-center': 'ai_content_moderation',
  'centralized-support-ticketing-system': 'ai_content_moderation',
  'interactive-topic-preference-collection-hub': 'interactive_topic_preference_collection_hub',
  'accessibility-analytics-preferences-center': 'accessibility_analytics_preferences_center',
  'global-localization-control-center': 'global_localization_control_center',
  'global-language-settings-hub': 'global_localization_control_center',
  'multi-authentication-gateway': 'multi_authentication_gateway',
  'community-elections-hub': 'community_elections_hub',
  'topic-based-community-elections-hub': 'topic_based_community_elections_hub',
  'enhanced-hubs-discovery-management-hub': 'enhanced_hubs_discovery_management_hub',
  'comprehensive-social-engagement-suite': 'comprehensive_social_engagement_suite',
  'community-engagement-dashboard': 'community_engagement_dashboard',
  'creator-community-hub': 'creator_community_hub',
  'smart-push-notifications-optimization-center': 'smart_push_notifications_optimization_center',
  'user-subscription-dashboard': 'user_subscription_dashboard',
  'enhanced-premium-subscription-center': 'enhanced_premium_subscription_center',
  'election-insights-predictive-analytics': 'election_insights_predictive_analytics',
  'advanced-search-discovery-intelligence-hub': 'advanced_search_discovery_intelligence_hub',
  'claude-ai-feed-intelligence-center': 'claude_ai_feed_intelligence_center',
  'context-aware-claude-recommendations-overlay': 'context_aware_claude_recommendations_overlay',
  'public-bulletin-board-audit-trail-center': 'public_bulletin_board_audit_trail_center',
  '3d-gamified-election-experience-center': '3d_gamified_election_experience',
  'voter-education-hub': 'voter_education_hub',
  'jolts-video-studio': 'jolts_video_studio',
  'elections-dashboard': 'elections_dashboard',
  'enhanced-election-results-center': 'elections_dashboard',
  'creator-reputation-election-management-system': 'creator_reputation_election_management_system',
  'voter-rolls-management': 'creator_reputation_election_management_system',
  'stripe-connect-account-linking-interface': 'stripe_connect_account_linking_interface',
  'stripe-connect-linking': 'stripe_connect_account_linking_interface',
  'stripe-payment-integration-hub': 'stripe_connect_account_linking_interface',
  'enhanced-creator-payout-dashboard-with-stripe-connect-integration': 'enhanced_creator_payout_dashboard_stripe_connect',
  'creator-brand-partnership-portal': 'creator_brand_partnership_portal',
  'creator-growth-analytics-dashboard': 'creator_growth_analytics_dashboard',
  'creator-revenue-forecasting-dashboard': 'creator_revenue_forecasting_dashboard',
  'creator-churn-prediction-intelligence-center': 'creator_churn_prediction_intelligence_center',
  'creator-marketplace-screen': 'creator_marketplace_screen',
  'creator-country-verification-interface': 'creator_country_verification_interface',
  'claude-creator-success-agent': 'claude_creator_success_agent',
  'predictive-creator-insights-dashboard': 'predictive_creator_insights_dashboard',
  'content-quality-scoring-claude': 'content_quality_scoring_claude',
  'enhanced-home-feed-dashboard': 'enhanced_home_feed_dashboard',
  'mcq-analytics-intelligence-dashboard': 'mcq_analytics_intelligence_dashboard',
  'mcq-a-b-testing-analytics-dashboard': 'mcq_ab_testing_analytics_dashboard',
  'fraud-detection-alert-management-center': 'fraud_detection_alert_management_center',
  'advanced-ai-fraud-prevention-command-center': 'fraud_detection_alert_management_center',
  'ai-dependency-risk-mitigation-command-center': 'fraud_detection_alert_management_center',
  'enhanced-predictive-threat-intelligence-center': 'fraud_detection_alert_management_center',
  'security-vulnerability-remediation-control-center': 'fraud_detection_alert_management_center',
  'auto-improving-fraud-detection-intelligence-center':
    'advanced_perplexity_fraud_intelligence_center',
  'predictive-anomaly-alerting-deviation-monitoring-hub': 'fraud_detection_alert_management_center',
  'advanced-perplexity-fraud-intelligence-center': 'advanced_perplexity_fraud_intelligence_center',
  'fraud-prevention-dashboard-with-perplexity-threat-analysis': 'advanced_perplexity_fraud_intelligence_center',
  'advanced-perplexity-fraud-forecasting-center': 'advanced_perplexity_fraud_forecasting_center',
  'advanced-ml-threat-detection-center': 'fraud_detection_alert_management_center',
  'zone-specific-threat-heatmaps-dashboard': 'fraud_detection_alert_management_center',
  'continuous-ml-feedback-outcome-learning-center': 'advanced_perplexity_fraud_intelligence_center',
  'perplexity-market-research-intelligence-center': 'advanced_perplexity_fraud_intelligence_center',
  'perplexity-strategic-planning-center': 'advanced_perplexity_fraud_forecasting_center',
  'perplexity-carousel-intelligence-dashboard': 'advanced_perplexity_fraud_intelligence_center',
  'dedicated-market-research-dashboard': 'advanced_perplexity_fraud_intelligence_center',
  'prediction-analytics-dashboard': 'advanced_perplexity_fraud_forecasting_center',
  'unified-incident-response-orchestration-center': 'unified_incident_response_orchestration_center',
  'unified-incident-response-command-center': 'unified_incident_response_orchestration_center',
  'automated-incident-response-portal': 'automated_incident_response_portal',
  'advanced-monitoring-hub-with-automated-incident-response': 'unified_incident_response_orchestration_center',
  'enhanced-incident-response-analytics': 'unified_incident_response_orchestration_center',
  'incident-response-analytics': 'unified_incident_response_orchestration_center',
  'custom-alert-rules-engine': 'unified_alert_management_center',
  'advanced-custom-alert-rules-engine': 'unified_alert_management_center',
  'unified-alert-management-center': 'unified_alert_management_center',
  'stakeholder-incident-communication-hub': 'unified_alert_management_center',
  'slack-team-alerts-center': 'unified_alert_management_center',
  'sms-emergency-alerts-hub': 'unified_alert_management_center',
  'sms-webhook-delivery-analytics-hub': 'unified_alert_management_center',
  'telnyx-sms-provider-management-center': 'unified_alert_management_center',
  'api-documentation-portal': 'api_rate_limiting_dashboard',
  'country-restrictions-admin': 'country_restrictions',
  'platform-integrations-admin': 'platform_integrations',
  // New advanced / infra features with existing toggles
  'stripe-subscription-management-center': 'stripe_subscription_management_center',
  'admin-subscription-analytics-hub': 'admin_subscription_analytics_hub',
  'status': 'public_status_page',
  'moments-creation-studio': 'public_status_page',
  'public-status-page': 'public_status_page',
  'mobile-operations-command-console': 'mobile_operations_command_console',
  'predictive-incident-prevention-24h': 'predictive_incident_prevention_24h',
  'real-time-performance-testing-suite': 'real_time_performance_testing_suite',
  'platform-testing-optimization-command-center': 'real_time_performance_testing_suite',
  'automated-security-testing-framework': 'real_time_performance_testing_suite',
  'performance-regression-detection': 'performance_regression_detection',
  'admin-automation-control-panel': 'admin_automation_control_panel',
  'analytics-export-reporting-hub': 'analytics_export_reporting_hub',
  'enhanced-resend-email-automation-hub': 'analytics_export_reporting_hub',
  'resend-email-automation-orchestration-center': 'analytics_export_reporting_hub',
  'res-tful-api-management-center': 'api_rate_limiting_dashboard',
  'webhook-integration-hub': 'analytics_export_reporting_hub',
  'advanced-webhook-orchestration-hub': 'analytics_export_reporting_hub',
  'executive-reporting-compliance-automation-hub': 'analytics_export_reporting_hub',
  'automated-executive-reporting-claude-intelligence-hub': 'analytics_export_reporting_hub',
  'api-rate-limiting-dashboard': 'api_rate_limiting_dashboard',
  'team-collaboration-center': 'api_rate_limiting_dashboard',
  'supabase-real-time-feed-ranking-engine': 'api_rate_limiting_dashboard',
  'open-ai-sms-optimization-studio': 'api_rate_limiting_dashboard',
  'unified-payment-orchestration-hub': 'unified_payment_orchestration_hub',
  'security-compliance-audit': 'security_compliance_audit_screen',
  'security-compliance-audit-screen': 'security_compliance_audit_screen',
  'security-compliance-automation-center': 'security_compliance_audit_screen',
  'cryptographic-security-management-center': 'security_compliance_audit_screen',
  'admin-payout-verification-dashboard': 'security_compliance_audit_screen',
  'vote-anonymity-mixnet-control-hub': 'security_compliance_audit_screen',
  'claude-ai-dispute-moderation-center': 'security_compliance_audit_screen',
  'international-payment-dispute-resolution-center': 'security_compliance_audit_screen',
  'compliance-dashboard': 'security_compliance_audit_screen',
  'compliance-audit-dashboard': 'security_compliance_audit_screen',
  'regulatory-compliance-automation-hub': 'security_compliance_audit_screen',
  'cost-analytics-roi-dashboard': 'cost_analytics_roi_dashboard',
  'automated-payout-calculation-engine': 'prize_distribution_tracking_center',
  'country-based-payout-processing-engine': 'prize_distribution_tracking_center',
  'multi-currency-settlement-dashboard': 'multi_currency_settlement_dashboard',
  'enhanced-multi-currency-settlement-dashboard': 'multi_currency_settlement_dashboard',
  'prize-distribution-tracking-center': 'prize_distribution_tracking_center',
  'real-time-winner-notification-prize-verification-center': 'prize_distribution_tracking_center',
  // Claude / Gemini / AI ops (Web routes wired to real pages Mar 2026)
  'anthropic-claude-revenue-risk-intelligence-center': 'creator_revenue_forecasting_dashboard',
  'claude-analytics-dashboard-for-campaign-intelligence': 'claude_ai_feed_intelligence_center',
  'claude-predictive-analytics-dashboard': 'claude_ai_feed_intelligence_center',
  'claude-ai-content-curation-intelligence-center': 'anthropic_content_intelligence_center',
  'claude-model-comparison-center': 'claude_ai_feed_intelligence_center',
  'claude-content-optimization-engine': 'content_quality_scoring_claude',
  'claude-decision-reasoning-hub': 'claude_decision_reasoning_hub',
  'unified-ai-decision-orchestration-command-center':
    'unified_incident_response_orchestration_center',
  'unified-ai-orchestration-command-center':
    'unified_incident_response_orchestration_center',
  'automatic-ai-failover-engine-control-center': 'live_platform_monitoring_dashboard',
  'gemini-fallback-orchestration-hub': 'live_platform_monitoring_dashboard',
  'ai-performance-orchestration-dashboard': 'real_time_performance_testing_suite',
  'ai-powered-performance-advisor-hub': 'real_time_performance_testing_suite',
  'open-ai-carousel-content-intelligence-center': 'content_distribution_control_center',
  'premium-2d-carousel-component-library-hub': 'content_distribution_control_center',
  'carousel-performance-analytics-hub': 'content_distribution_control_center',
  'carousel-ab-testing-dashboard': 'content_distribution_control_center',
  'advanced-carousel-roi-analytics-dashboard': 'content_distribution_control_center',
  'carousel-feed-orchestration-engine': 'content_distribution_control_center',
  'creator-carousel-optimization-studio': 'content_distribution_control_center',
  'advanced-carousel-fraud-detection-prevention-center': 'content_distribution_control_center',
  'real-time-carousel-monitoring-hub': 'content_distribution_control_center',
  'carousel-health-scaling-dashboard': 'content_distribution_control_center',
  'autonomous-claude-agent-orchestration-hub': 'unified_incident_response_orchestration_center',
  'enhanced-real-time-behavioral-heatmaps-center': 'fraud_detection_alert_management_center',
  'gemini-cost-efficiency-analyzer-case-report-generator': 'live_platform_monitoring_dashboard',
  'gemini-cost-efficiency-analyzer': 'live_platform_monitoring_dashboard',
  'ai-powered-predictive-analytics-engine': 'election_insights_predictive_analytics',
  'unified-ai-performance-dashboard': 'real_time_performance_testing_suite',
  'comprehensive-health-monitoring-dashboard': 'live_platform_monitoring_dashboard',
  'production-monitoring-dashboard': 'live_platform_monitoring_dashboard',
  'production-deployment-hub': 'live_platform_monitoring_dashboard',
  'app-performance-dashboard': 'live_platform_monitoring_dashboard',
  'supabase-advisor-verification-dashboard': 'live_platform_monitoring_dashboard',
  'ml-model-training-interface': 'claude_ai_feed_intelligence_center',
  'load-testing-performance-analytics-center': 'real_time_performance_testing_suite',
  'production-load-testing-suite': 'real_time_performance_testing_suite',
  'performance-optimization-engine-dashboard': 'performance_regression_detection',
  'real-time-web-socket-monitoring-command-center': 'live_platform_monitoring_dashboard',
  'automated-data-cache-management-hub': 'live_platform_monitoring_dashboard',
  'advanced-supabase-real-time-coordination-hub': 'live_platform_monitoring_dashboard',
  'enhanced-real-time-web-socket-coordination-hub': 'live_platform_monitoring_dashboard',
  'enhanced-performance-monitoring-dashboard': 'live_platform_monitoring_dashboard',
  'real-time-mcq-sync-monitor-dashboard': 'live_platform_monitoring_dashboard',
  'real-time-threat-correlation-dashboard': 'live_platform_monitoring_dashboard',
  'real-time-threat-correlation-intelligence-hub': 'live_platform_monitoring_dashboard',
  // Enterprise / admin audit (platform_feature_toggles: unified_admin_activity_log,
  // admin_platform_logs_center, enterprise_white_label, enterprise_sso)
  'unified-admin-activity-log': 'unified_admin_activity_log',
  'admin-platform-logs-center': 'admin_platform_logs_center',
  'enterprise-operations-center': 'enterprise_white_label',
  'white-label-election-platform': 'enterprise_white_label',
  'enterprise-sso-integration-hub': 'enterprise_sso',
  'bulk-election-creation-hub': 'enterprise_white_label',
  'enterprise-analytics-hub': 'enterprise_white_label',
  'enterprise-api-access-center': 'enterprise_white_label',
  'custom-branding-options-center': 'enterprise_white_label',
  'sla-backed-infrastructure-center': 'enterprise_white_label',
  'enterprise-compliance-reports-center': 'enterprise_white_label',
  'volume-pricing-licensing-center': 'enterprise_white_label',
  'dedicated-account-manager-center': 'enterprise_white_label',
  'whatsapp-notifications-center': 'enterprise_white_label',
  // Revenue intelligence / regional (platform_feature_toggles — seed_comprehensive_audit_toggles)
  'unified-revenue-intelligence-dashboard': 'unified_revenue_intelligence_dashboard',
  'unified-business-intelligence-hub': 'unified_revenue_intelligence_dashboard',
  'real-time-revenue-optimization-engine': 'unified_revenue_intelligence_dashboard',
  'ai-sentiment-strategy-analytics': 'unified_revenue_intelligence_dashboard',
  'anthropic-security-reasoning-integration-hub': 'unified_revenue_intelligence_dashboard',
  'enhanced-admin-revenue-analytics-hub': 'unified_revenue_intelligence_dashboard',
  'financial-tracking-zone-analytics-center': 'unified_revenue_intelligence_dashboard',
  'country-revenue-share-management-center': 'country_revenue_share_management_center',
  'regional-revenue-analytics-dashboard': 'regional_revenue_analytics_dashboard',
  'security-monitoring-dashboard': 'security_monitoring_dashboard',
};

/**
 * Get feature_key for a route path (with or without leading slash).
 * @param {string} path - e.g. '/election-creation-studio' or 'election-creation-studio'
 * @returns {string|null} feature_key or null if route is not gated
 */
export function getFeatureKeyForPath(path) {
  if (!path || typeof path !== 'string') return null;
  const normalized = path.replace(/^\//, '').split('?')[0];
  return ROUTE_FEATURE_KEYS[normalized] ?? null;
}
