/**
 * Map route path (no leading slash) to platform_feature_toggles.feature_key.
 * Used to gate routes by admin On/Off panel. Keys must match DB feature_key.
 * If a path is not in this map, the route is not gated by feature toggle.
 */
export const ROUTE_FEATURE_KEYS = {
  'election-creation-studio': 'election_creation',
  'vote-verification-portal': 'vote_verification_portal',
  'blockchain-audit-portal': 'blockchain_verification',
  'secure-voting-interface': 'secure_voting_interface',
  'vote-in-elections-hub': 'vote_in_elections_hub',
  'voting-categories': 'voting_categories',
  'collaborative-voting-room': 'collaborative_voting_room',
  'location-based-voting': 'location_based_voting',
  'vottery-points-vp-universal-currency-center': 'vp_universal_currency_center',
  'comprehensive-gamification-admin-control-center': 'gamified_elections',
  'dynamic-quest-management-dashboard': 'dynamic_quest_management_dashboard',
  'election-prediction-pools-interface': 'prediction_pools',
  'unified-gamification-dashboard': 'unified_gamification_dashboard',
  'user-profile-hub': 'user_profile_hub',
  'digital-wallet-hub': 'digital_wallet_hub',
  'direct-messaging-center': 'direct_messaging',
  'notification-center-hub': 'notification_center_hub',
  'friends-management-hub': 'friends_management_hub',
  'social-activity-timeline': 'social_activity_timeline',
  'settings-account-dashboard': 'settings_account_dashboard',
  'personal-analytics-dashboard': 'personal_analytics_dashboard',
  'user-analytics-dashboard': 'user_analytics_dashboard',
  'user-security-center': 'user_security_center',
  'participatory-ads-studio': 'participatory_advertising',
  'vottery-ads-studio': 'participatory_advertising',
  'campaign-management-dashboard': 'campaign_management_dashboard',
  'advertiser-analytics-roi-dashboard': 'advertiser_analytics_roi',
  'brand-advertiser-registration-portal': 'brand_advertiser_registration',
  'creator-monetization-studio': 'creator_monetization_studio',
  'creator-success-academy': 'creator_success_academy',
  'enhanced-mcq-creation-studio': 'enhanced_mcq_creation_studio',
  'enhanced-mcq-pre-voting-interface': 'mcq_pre_voting_interface',
  'live-question-injection-management-center': 'live_question_injection_management_center',
  'enhanced-mcq-image-interface': 'enhanced_mcq_image_interface',
  'interactive-onboarding-wizard': 'interactive_onboarding_wizard',
  'ai-guided-interactive-tutorial-system': 'ai_guided_interactive_tutorial_system',
  'user-feedback-portal-with-feature-request-system': 'user_feedback_portal_feature_request_system',
  'feature-implementation-tracking-engagement-analytics-center': 'feature_implementation_tracking_engagement_analytics_center',
  'content-moderation-control-center': 'ai_content_moderation',
  'interactive-topic-preference-collection-hub': 'interactive_topic_preference_collection_hub',
  'accessibility-analytics-preferences-center': 'accessibility_analytics_preferences_center',
  'global-localization-control-center': 'global_localization_control_center',
  'multi-authentication-gateway': 'multi_authentication_gateway',
  'community-elections-hub': 'community_elections_hub',
  'topic-based-community-elections-hub': 'topic_based_community_elections_hub',
  'enhanced-groups-discovery-management-hub': 'enhanced_groups_discovery_management_hub',
  'comprehensive-social-engagement-suite': 'comprehensive_social_engagement_suite',
  'community-engagement-dashboard': 'community_engagement_dashboard',
  'smart-push-notifications-optimization-center': 'smart_push_notifications_optimization_center',
  'user-subscription-dashboard': 'user_subscription_dashboard',
  'enhanced-premium-subscription-center': 'enhanced_premium_subscription_center',
  'election-insights-predictive-analytics': 'election_insights_predictive_analytics',
  '3d-gamified-election-experience-center': '3d_gamified_election_experience',
  'voter-education-hub': 'voter_education_hub',
  'elections-dashboard': 'elections_dashboard',
  'creator-reputation-election-management-system': 'creator_reputation_election_management_system',
  'stripe-connect-account-linking-interface': 'stripe_connect_account_linking_interface',
  'enhanced-creator-payout-dashboard-with-stripe-connect-integration': 'enhanced_creator_payout_dashboard_stripe_connect',
  'creator-brand-partnership-portal': 'creator_brand_partnership_portal',
  'creator-growth-analytics-dashboard': 'creator_growth_analytics_dashboard',
  'creator-churn-prediction-intelligence-center': 'creator_churn_prediction_intelligence_center',
  'creator-marketplace-screen': 'creator_marketplace_screen',
  'creator-country-verification-interface': 'creator_country_verification_interface',
  'claude-creator-success-agent': 'claude_creator_success_agent',
  'predictive-creator-insights-dashboard': 'predictive_creator_insights_dashboard',
  'enhanced-home-feed-dashboard': 'enhanced_home_feed_dashboard',
  'mcq-analytics-intelligence-dashboard': 'mcq_analytics_intelligence_dashboard',
  'mcq-a-b-testing-analytics-dashboard': 'mcq_ab_testing_analytics_dashboard',
  'fraud-detection-alert-management-center': 'fraud_detection_alert_management_center',
  'advanced-perplexity-fraud-intelligence-center': 'advanced_perplexity_fraud_intelligence_center',
  'advanced-perplexity-fraud-forecasting-center': 'advanced_perplexity_fraud_forecasting_center',
  'unified-incident-response-orchestration-center': 'unified_incident_response_orchestration_center',
  'automated-incident-response-portal': 'automated_incident_response_portal',
  'country-restrictions-admin': 'country_restrictions',
  'platform-integrations-admin': 'platform_integrations',
  // New advanced / infra features with existing toggles
  'stripe-subscription-management-center': 'stripe_subscription_management_center',
  'admin-subscription-analytics-hub': 'admin_subscription_analytics_hub',
  'status': 'public_status_page',
  'public-status-page': 'public_status_page',
  'mobile-operations-command-console': 'mobile_operations_command_console',
  'predictive-incident-prevention-24h': 'predictive_incident_prevention_24h',
  'real-time-performance-testing-suite': 'real_time_performance_testing_suite',
  'performance-regression-detection': 'performance_regression_detection',
  'admin-automation-control-panel': 'admin_automation_control_panel',
  'analytics-export-reporting-hub': 'analytics_export_reporting_hub',
  'api-rate-limiting-dashboard': 'api_rate_limiting_dashboard',
  'unified-payment-orchestration-hub': 'unified_payment_orchestration_hub',
  'security-compliance-audit-screen': 'security_compliance_audit_screen',
};

/**
 * Get feature_key for a route path (with or without leading slash).
 * @param {string} path - e.g. '/election-creation-studio' or 'election-creation-studio'
 * @returns {string|null} feature_key or null if route is not gated
 */
export function getFeatureKeyForPath(path) {
  if (!path || typeof path !== 'string') return null;
  const normalized = path.replace(/^\//, '').split('?')[0];
  return ROUTE_FEATURE_KEYS[normalized] ?? null;
}
