import React, { useState, useEffect } from 'react';
import Icon from './AppIcon';
import { constitutionalService } from '../services/constitutionalService';

const LogicAuditModal = ({ isOpen, onClose, contentItem, userId }) => {
  const [explanation, setExplanation] = useState('');
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    if (isOpen && contentItem) {
      const fetchAudit = async () => {
        setIsLoading(true);
        const res = await constitutionalService.getLogicAuditExplanation(userId, contentItem);
        setExplanation(res.explanation);
        setIsLoading(false);
      };
      fetchAudit();
    }
  }, [isOpen, contentItem, userId]);

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-[1000] flex items-center justify-center p-4">
      <div className="absolute inset-0 bg-black/60 backdrop-blur-sm" onClick={onClose} />
      <div className="relative w-full max-w-lg bg-card border border-white/10 rounded-2xl p-8 shadow-2xl animate-in fade-in zoom-in-95 duration-200">
        <header className="flex items-center justify-between mb-6">
          <div className="flex items-center gap-3 text-primary">
            <Icon name="Scale" size={24} />
            <h2 className="text-xl font-bold tracking-tight">LOGIC AUDIT</h2>
          </div>
          <button onClick={onClose} className="p-2 hover:bg-white/5 rounded-full transition-colors">
            <Icon name="X" size={20} />
          </button>
        </header>

        <div className="space-y-6">
          <div>
            <div className="text-[10px] uppercase tracking-widest text-muted-foreground font-black mb-1">Target Content</div>
            <div className="text-sm font-semibold">{contentItem?.title || contentItem?.content}</div>
          </div>

          <div className="p-4 rounded-xl bg-primary/5 border border-primary/10">
            <div className="text-[10px] uppercase tracking-widest text-primary font-black mb-3">Constitutional Explanation</div>
            {isLoading ? (
              <div className="flex items-center gap-2 text-sm text-muted-foreground italic">
                <Icon name="Loader2" size={16} className="animate-spin" />
                Auditing merit-based routing...
              </div>
            ) : (
              <p className="text-sm leading-relaxed text-foreground/90">
                {explanation}
              </p>
            )}
          </div>

          <div className="grid grid-cols-3 gap-4">
            <MetricBox label="Merit (vIQ)" value={(contentItem?.viq_metadata?.vIQ * 100 || 75).toFixed(0) + '%'} color="text-green-500" />
            <MetricBox label="Personal" value={(contentItem?.viq_metadata?.personalizationScore * 100 || 45).toFixed(0) + '%'} color="text-blue-500" />
            <MetricBox label="Discovery" value={(contentItem?.viq_metadata?.discoveryScore * 100 || 30).toFixed(0) + '%'} color="text-purple-500" />
          </div>

          <footer className="pt-4 border-t border-white/5">
            <div className="text-[10px] text-muted-foreground italic leading-tight">
              * This explanation is generated by Gemini 1.5 Pro based on your democratic participation history and real-time merit signals. 
              Vottery V1 ensures 100% commercial neutrality in ranking.
            </div>
          </footer>
        </div>
      </div>
    </div>
  );
};

const MetricBox = ({ label, value, color }) => (
  <div className="bg-white/5 rounded-xl p-3 border border-white/5">
    <div className="text-[8px] uppercase tracking-tighter text-muted-foreground font-bold mb-1">{label}</div>
    <div className={`text-lg font-black ${color}`}>{value}</div>
  </div>
);

export default LogicAuditModal;
